version: '3.8'

services:
	database:
		image: postgres
		container_name: database_pandora
		restart: always
		ports:
			- 5432:5432
		environment:
			- POSTGRES_USER=pandora
			- POSTGRES_PASSWORD=p@nd0r@2022++
			- POSTGRES_DB=pandora
		volumes:
			- pgdata:/data/postgres

volumes:
	pgdata:
		driver: local